name: Build Data app repo

on:
  repository_dispatch:

jobs:
  build_pages:
    name: Build from data repository
    runs-on: ubuntu-latest
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Install
        run: |
          sudo bash install.sh
      - name: Install Ant-Contrib
        run: |
          wget https://repo1.maven.org/maven2/ant-contrib/ant-contrib/1.0b3/ant-contrib-1.0b3.jar
          mv ant-contrib-1.0b3.jar /usr/share/ant/lib
      - name: Get Data
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "KfNGOe/zinzendorf-data"
          file: "data.zip"
          target: "data.zip"
          token: ${{ secrets.ACCESS_TOKEN }} 
          #Token has to be set in github actions secrets: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
          #https://docs.github.com/en/actions/security-guides/encrypted-secrets
      - name: Unzip Data
        run: |
          rm -rf data/
          unzip data.zip -d data
          rm data.zip      
      - name: Build
        run: |
          . build.sh      
      - name: Zip Html folder
        run: |
          zip -r html.zip html/
      - name: Set outputs
        id: vars
        run: echo "timestap=$(date +%s)" >> $GITHUB_ENV
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.timestap }}
      - name: Create Release
        id: create_release
        uses: juitnow/github-action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ env.timestap }}
          release_name: Release ${{ env.timestap }}
          body: Generated Release
          draft: false
          prerelease: false
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./html.zip
          asset_name: html.zip
          asset_content_type: application/gzip
      - name: Pushes to kfngoe.github.io
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: "html"
          destination-github-username: "KfNGOe"
          destination-repository-name: "kfngoe.github.io"
          user-email: ferdinand-I-app@github.io
          target-branch: main
